const Aries= {
    Mercury: "If you have Mercury in Aries, you tend to be witty, outspoken and original. There is a sharp edge to your conversation, an ironic or sarcastic tone that can sometimes be biting and sometimes very funny.",
    Venus: "You are the kind of person who falls in love at first sight and never thinks once before following the dictates of your heart. People with Venus in aries are a curious mixture of sentimentality and aggressiveness.",
    Mars: "As a Mars-Arian, you are given self-confidence and force of character. Others always know how you feel about a supject because you tell them under no uncertain terms.",
    Jupiter: "Luck follows you in professions where you can be your own boss. You are discontent when you have to follow people's orders and, being independent and brash, you immediately try to change that situation.",
    Saturn: "Saturn brings delay to Aries, the sign of initiative, and the result is confusion. If you are a Saturn-Arien you can be strong and powerful one minute and irresolute and wavering the next. This position is not an easy one, for you must continually fight against obstacles placed in your way.",
    Uranus: "What you want is to see things clearly and not be a victim of confused or disorganized thinking. You immediately try to put your own ideas into action and have little patience with tried-and-true methods. You believe people who play it safe are usually sorry.",
    Neptune: "(1861/62- 1874/75) To Aries, the sign of active energy, Neptune brings a reforming spirit and high ideals. They are idealistis and revolutionaries. When Neptune was last in Aries, it was a time of upheaval. Darwin's theory of evolution shook long-established concepts about man's history. The American Civil War was fought for the ideal of equality among human beings.",
    Pluto: "(1822/23- 1851/53) Pluto's influence in this adventurous sign set off the great pioneering trek westward to America. It was during this era that the world became larger as mankind ventured to explore the far reaches of this planet. When Pluto is in Aries, the planet's personal influence gives courage, self-reliance and a strong sense of individuality; recklessness and egotism are negative effects for individuals."
}



const Taurus= {
    Mercury: "You have an excellent memory and are a good observer, but you are apt to listen inattentively; since you're not about to change your mind. You also have a tendency to repeat yourself, to state what you've said over again in different terms, usually to make sure everyone has gotten the point.",
    Venus: "As a Venus-in-Taurus person you are affectionate and romantive, but you dont give your love away too quckly. A bad love affair is hard on you emotionally so you take your time deciding on the right person to love. This process, however, is done by feeling rather than thinking logically.",
    Mars: "If you have a Mars in Taurus, you tend to triupmh through your own determined and persistent efforts. Your vitality is a slow and steady foce that drives you on to success.",
    Jupiter: "Jupiter and Taurus are very harmonious; Taurus is the money sign of the zodiac and Jupiter brings abundance. As a Jupiter- Taurean you have an eye for beauty and art. You tend to collect items that often increase in value.",
    Saturn: "With this saturn position you are determined and capable, and take responsibility seriously. Once you achieve material comfort (usually later in life), you are generous to others in need, for you understand what it means to not have enough.",
    Uranus: "Uranus in Taurus helps you to produce results through patient and concerted effort. You need to build, to be constructive and to achieve. A taste for bright colors and vivid patterns is evident in the way you dress and decorate.",
    Neptune: "(1874/75- 1887/89) Neptune in the materialistic sign of Taurus brings a deeper awareness of what is truly valuable in life. These people are able to make practical use of (and sometimes profit from) their interest in mysticism. When Neptune was last in Taurus we had the great expansion of American industrialism, and along with it a revival of interest in mysticism and the occult. During this era the writings of Karl Marx gave rise to new idealism about the distribution of wealth.",
    Pluto: "(1851/53- 1882/84) In Taurus, the sign of wealth and possessions, Pluto brought upheaval. In America, a bloody civil war was fought over the question of slavery- whether one human being could properly be the possession of another. All over the world the very wealthy exploited the very poor. During this era Karl Marx formulated his revolutionary theories based on the elimination of the class system and more equal distribution of wealth. When Pluto is in Taurues, the planet's personal influence gives its natives determination and endurance."
}

const Gemini= {
    Mercury: "Because you have such a variety of interests, your grasp of knowledge tends to be superficial. You always know a bit about everything, but sometimes not a lot about anything. You are clever enough to conceal this and to give a marvelous impression of being well informed.",
    Venus: "If you have Venus in Gemini you must have an intellectual rapport with someone before you affection begins to blossom. Basically, you have a lighthearted attitude towards love. Intense, heavy emotional commitments are like and anchor around your neck.",
    Mars: "Mars in Gemini favors energetic activity of the mind. You are brilliantly intellectual with a steel-trap brain that quickly grasps concepts and spins new ideas.",
    Jupiter: "Though you dont necessarily look for moneymaking opportunities, these usually come to you through the many friends and contacts that you acquire. As a Jupiter-in-Gemini person you are very versitle and clever, and often make a name for yourself in more than one profession.",
    Saturn: "With Saturn in Gemini, you have a sharp mind that is deepend with undersanding under this planet's steadying influence. You have a happy combination of native wisdom and a youthful wish to learn. You prosper when engaged in work that requires both patience and intelligence.",
    Uranus: "You are intellectual and imaginative. You posses a magnetic mind that draws people to you, and you have the ability to sway others to your point of view. Even in ordinary communication, such as phone calls and letters, you are original and captivating and your amusing way with words is evident.",
    Neptune: "(1887/89- 1901/02) In Gemini, Neptune bestows mental genuis, imagination, and creativity. Neptune-Geminis have a magnetic ability to express themselves, a hypnotic way of communicating. When Neptune was last in Gemini, Henry Ford perfected the automobile and the Wright brothers built a prototype of the first airplane. Neptune-Geminis are resourceful, versatile and perceptive.",
    Pluto: "(1882/84- 1912/14) When Pluto was last in Gemini, the sign of communication, it revolutionized the way information reached the masses. This was the era when newspapers came into prominence. Gemini rules the airwaves so its not surprising that during Pluto's transit the telegraph, the radio and telephone came into being. When Pluto is in Gemini the planet's personal influence gives its natives an inventive and restless mind that seeks change and freedom from old restrictions."

}

const Cancer= {
    Mercury: "As a native of this Mercury position, you are sensitive to what others think about you. You are chameleonlike in the way you are able to adapt yourself to different kinds of people. This doesn't mean, however, that you don't cling possesively to your own ideas.",
    Venus: "Being loved is more important to you than anything else, though you often conceal this need under a shell of reserve. You are not, however, so blindly romatic that you dont carefully consider future security.",
    Mars: "You have great strength of will but it is never thrust into the open. Like the tides, you wear down opposition by repeated assualt. Each wave may accomplish little but the accumulated effect is overpowering.",
    Jupiter: "As a Jupiter-Cancerian, you have a wonderful disposition, are good-humored, funny and optimistic. You are popular wherever you go, and this opens many doors for you. You are imaginative and sympathetic, and do well in creative pursuits.",
    Saturn: "Saturn encourages too much dependence on others in this emotional and clinging sign. You are, however, superb at seeing a task through to completion. You are also ambitious and strive to find material wealth to make your life secure.",
    Uranus: "You have a highly developed imagination and a subconcious that borders on psychic awareness. Your intuitions can be trusted. Many of you have a reputation for being eccentric and unpredictable and for having an artistic temperament.",
    Neptune: "(1901/02- 1914/16) In the emotional sign of Cancer, Neptune's influence gives a psychic, spiritual, and idealistic quality. Neptune-Cancers are sensitive and compassionate. When Neptune was last in Cancer, the American movement of social protest was part of a change affecting Western civilization.",
    Pluto: "(1912/14- 1937/39) Pluto's stormy transit through Cancer, the sign of home, brought upheaval to family life in America. By the millions people left the country to settle in towns and cities. The negative side of Pluto-in-Cancer was shown in the hideous loss of life in World War One and the preparations for World War Two under the leadership of militaristic Nazi Germany, a nation that espoused glorification of the homeland. Our country and our way of life (Cancerian values) were imperiled."
}

const Leo= {
    Mercury: "If you are a native of this position you have a magnetic flair for dealing with people. It;s true that you can be boastful, arrogant and bombstastic, and if things don't go your way your fiery temper may ignite. But basically you have such a kind heart and sunny disposition that people usually forgive you.",
    Leo: "You are extravagantly affectionate and generous, buying expensive gifts for those you love and praising them to the skies in front of other people. Of course, what you must have back is intense devotion, loyalty and lots of attention. You must always be dominant in a love affair.",
    Mars: "With mars in this position in your chart you are never ordinary. You make grand plans and posses the force and drive to put them into action. No one can grab attention and affection of others the way you can.",
    Jupiter: "Your full potential is achieved through leadership, you are wretchedly unhappy if forced to stay on the lowest rung. Jupiter gives you personal charm and warmhearted vitality. Other people want to do things for you, and you often benefit from influential friends.",
    Saturn: "You are good at organizing people and assuming responsibility. As a Saturn-Leo, you have an instinct for knowing how to draw a public to you. You fear appearing mediocre and ordinary, and you hide feelings of envy and jealousy because this is a weakness you'll never admit to.",
    Uranus: "As a native of this position, you have a forceful personality and express yourself through leadership. Your creative mind constantly spins new ideas, but you are not content to merely see your ideas carried out. You must be on display as well; you want the credit and the attention.",
    Neptune: "(1914/15- 1928/29) In the noble sign of Leo, Neptune confers great courage and ability for leadership. Leo is also the sign of drama, and during Neptune's transit of Leo we saw the rise of the motion picture industry to dominance in the field of entertainment. This was also the flamboyant era of the Roaring Twenties.",
    Pluto: "(1937/39- 1956/58) When Pluto is in Leo, the personal influence is to emphasize love of power, a domineering ego, and self-aggrandizement, but it also confers it's natives with strong pride and a will to prevail despite obstacles. The generation that was born when Pluto transited Leo introduced the era of the pleasure principle; There is also a strong emphasis on mass hero-worship of personalities in the media."
}

const Virgo= {
    Mercury: "You like to deal with facts; before you make up your mind you must know all sides to the question and get all the information avaliable in order to analyze it. Once you form a theory, you're quite conviced its the truth. Thenceforward, you expect reality to conform to your ideas, rather than vice versa.",
    Leo: "If you have Venus in Virgo, you tend to be cautious about falling in love. You hold yourself on a tight rein, because you fear that your feelings will be exploited by someone unworth. What you want in a love relationship is someone who will regard you as special.",
    Mars: "You are ambitious and proud, though this is not always apparent on the surface. Extremely strong-willed, you can seperate yourself from you emotions when it comes to making decisions.",
    Jupiter: "The power of Jupiter surrounds you in intellectual pursuits, but the difference between Jupiter-Virgos and other intellectual signs is that Virgos have an uncommon amount of common sense. You are also superb at handling detail and do your best work a step at a time.",
    Saturn: "You are methodical and orginaized, willing to work hard to achieve goals. To you, theory and practice are one and the same; you immediately put what you learn into use. You can become bogged down in trivialities because you are a stickler for details.",
    Uranus: "You seek complete autonomy when carrying out your ideas, and rebel against routine and the restrictions of others. Your independence is sometimes so marked as to be considered eccentric to others.",
    Neptune: "(1928/29- 1942/43) The spritual planet Neptune in the practical sign of Virgo gives a strong instinct for service to mankind. Many of those born when Neptune was in Virgo- the tumultuous years of the Great Depression and onset of WW2- have in our day become active civil rights, the women's movement, and environmental concerns. When Neptune transited Virgo, the sign of health, treatment of disease with penicillin became widespread and chemotherapy was introduced.",
    Pluto: "(1956/58- 1971/72) During Pluto's transit of Virgo, the sign of service to others, the Kennedy and Johnson administrations were committed to social programs. In this sign of health, some of Pluto's influences on its generation are a new awareness of toxic food additives, and emphasis on holistic medicine, and concern over pollution of the environment. When Pluto is in Virgo, the planet's personal influence bestows a profound analytical quality to the personality. People under this influence seek perfection but are also suspicious and ready to find fault with the world around them."
}

const Libra= {
    Mercury: "What you want is to make the perfect choice. Even after you've made up your mind, however, it isn't definite. A favorite ploy is to adopt the wait-and-see attitude. In truth you have fin intuitions and often know things in a flash. But then you tend to intellectualize and go off in the wrong direction.",
    Venus: "You are in love with love. However, you are much more romantic than sensual. To you, true love is of the spirit. People who dont measure up are summarily dismisse no matter what their deeper qualities may be. Venus-in-Libra can be cold and aloof toward anyone who presumes.",
    Mars: "You are idealistic and esthetic; crudeness of any kind turns you off. Mars-Librans believe passionately in fair play. You have an enviable ability to make a pleasing impression on the public.",
    Jupiter: "Luck comes to you through your artistic talents and your eye for beauty and harmony. Jupiter-Librans are most successful in partnerships; you should never start a business completely on your own. Your finely balanaced reason and impartiality would make you an excellent judge, lawyer or diplomat.",
    Saturn: "As a Saturn-Libran, you are gifted with good judgement and an instinct for making the right impression on others. You know when to be aggressive and when to be diplomatic. Saturn in Libra may suppress the desire to share and be close to another person, which often results in loneliness.",
    Uranus: "As a native of this position, you are drawn to unusual relationships and are often thought of as unconventional in your choice of friends or lovers. In this Uranus position, love affairs and marriages tend to begin quickly and to have abrupt endings. You posses an appealing charm in the way you present yourself or dress.",
    Neptune: "(1942/43- 1955/57) Neptune in the romantic sign of Libra emphasizes idealism and love. Those born while Neptune transited Libra have been called the love generation. Libra is also the sign of partnership and marriage; this era brought a new quesitoning of the values of marriage, with a resultant rise in divorce and search for happiness in love.",
    Pluto: "(1971/72- 1983/84) Libra is the sign of peace and harmony, and early in Pluto's journey through Libra the agonizing war in Vietnam finally came to an end. Libra emphasizes egalitarianism and equality, and Pluto's transit saw the passage of equal opportunity laws, support for the Equal Rights Amendment, and greater equality for homosexuals. When Pluto is in Libra, the planet's personal influence promotes a deep need to seek harmony and cooperation. Its negative side brings unforseen problems and disruption in close relationships."
}

const Scorpio= {
    Mercury: "As a Mercury-in-Scorpio person, you are questioning and probing. You must dig beneath the surface to discover the real facts. You take great pride in your ability to not be fooled. One cannot budge you from a point of view unless you want to be budged.",
    Venus: "With your Venus in Scorpio, being in love is an all-consuming experience for you. There is a profound intensity to your emotions. Your deep need is to possess a lover wholly, to make your partner surrender to you body and soul. You are very sensitive to any rebuff; you can bristle like a porcupine.",
    Mars: "Mars in Scorpio underscores persistence and intensity. Your efforts are well disciplined, always directed toward a purpose. There are no wasted movements or needless expenditures of energy.",
    Juptier: "Jupiter in Scorpio is a very powerful incluence on willpower and personal magnetism. Many Jupiter-Scorpios excel at ferreting out hidden information. Luck comes to you through your strong attraction for the opposite sex.",
    Saturn: "You understand human motivation, which enables you to control others. Your dominating strength is often hidden under a pleasant or genial exterior. Your strong will can become inflexible. Once you set on a course, you see it through to the end.",
    Uranus: "You have a domination quality that wells up from deep within you. You possess a magnetic sexuality that is sometimes known as star quality. You are blessed with a penetrating mind. You are able to bring concentration and willpower to bear, and thus can move mountains through sheer effort.",
    Neptune: "(1955/57- 1970) In the powerful sign of Scorpio, Neptune's influence is shown in the depth and intensity of feeling. Neptune-Scorpios are drawn to what is hidden from public view and want to uncover the truth. In years to come, this generation will continue to fight for more open government and to rectify the probable secret damage dome to our environment by ruthless profitseekers.",
    Pluto: "(1983/84- 1995) Pluto is extremely powerful in Scorpio, the sign that it rules, and this period was one of turmoil and revolution. Scorpio is the sign of destruction, and Pluto's transit was rife with world-wide terrorism. Pluto's link to the underworld was seen in the rise of an international drug trade. Pluto's personal influence in Scorpio produces individuals with penetrating minds and strong wills. These people are imaginative and passionate, posses psychic ability, and can ruthless about getting their own way."
}

const Sagittarius= {
    Mercury: "If you have this position of Mercury you are quick and bright, breezy, to the point. You prize freedom of expression and cannot bear the thought of any power of censorship over what you have to say. Your mind is restless, inquiring, always looking for stimulation.",
    Venus: "First attractions are always wildly romantic; as a Venus-Sagittarian you will never seem to have commonplace for banal love affairs. However, you cannot sustain the emotion, and therefore never completely surrender your freedom to another person.",
    Mars: "In Sagittarius, the power of Mars exhibits itself in brilliant flashes. It promotes courage, independence and daring. Dashing and exciting as your actions may be, you are easily distracted.",
    Jupiter: "With this Jupiter position, you are a person who likes to live well; You have a free hand when it comes to spending. Fortunately, you usually attract financial luck. No other Jupiter position augurs as much success in this area. As a native, you have an instict for turning ideas into cash.",
    Saturn: "Saturn gives your mind a philosophical bent; you can usually face up to what life offers because you put your faith in the long-term outcome. As a Saturn-Sagittarian you experience inner conflict between your need for order and security and your desire to seek adventure and challenge.",
    Uranus: "You are very independent and rebel against anything overly organized and structured. At times you are restless and quite reckless. You are proud and couragous and often have an unconventional point of view.",
    Neptune: "(1970- 1984) In the altruistic sign of Sagittarius, Neptune has an uplifting influence. Neptune in this sign brings a desire for liberty and truth, and a visionary outlook. While Neptune transited this sign of travel and expansion, more people had access to foriegn cultures through travel, research and the World Wide Web.",
    Pluto: "(1995- 2007/08) Sagittarius is the sign of truth and open knwoledge, and the years just prior to the turn of the millennium are characterized as the Information Age. Sagittarius also represents foreign lands and far-flung places and, through the computer and Internet, Pluto has transformed the concept of distance. International trade and business takes place in seconds, retailers sell to the public directly through the computer, and e-mail instantly connects people on opposite sides of the Earth. Pluto-in-Sagittarius brings deep hope and profound understanding. It's negative influence is toward impractical extremes, but the optimism and enthusiasm that characterizes this transit should make this an uplifting time for human beings everywhere."
}

const Capricorn= {
    Mercury: "You are not only superb at handling detail, but you also never lose sight of the whole picture. You always have an objective; you always have a secret goal you are pursuing. A problem you have in relating to people can be your dictorial manner, though a redeeming trait is your dry sense of humor.",
    Venus: "When in love you are faithful and dependable. You may not be demonstrative and flowery, but what you say you mean. There is a dichotomy between your emotional life and your sexuality; You have earthly passions but keep them seperate from your mental attitude.",
    Mars: "As a person with this Mars position, you are fierce, magnetic and commanding. Your stregth lies in your obstinacy and ability to endure. You have vigor and dynamice force, and also quiet self-reliance.",
    Jupiter: "In the strong, materialistic sign of Capricon, Jupiter's power is expressed through ambition. Success isn't a flash in the pan with you. It is achieved gradually, but over the longterm you tend to reach the top because you are disciplined.",
    Saturn: "You are ambitious and independent, dedicated and unswerving, but your methods can be dictatorial and overbearing and you may sometimes be thought of as selfish and mean. You want to do everything yourself. You also have an instinct for doing things the hard way; you don't listen to advice. However, you do learn from experience.",
    Uranus: "You have a strong inner will to succeed. You need to be in authority and have difficulty accepting the rule of other people. You have an ability to to spot future trends and move in a more lucrative direction. Uranus gives you confidence to break through old established ideas.",
    Neptune: "(1984/85- 1998) In the disciplined sign of Capricorn, Neptune's power is practical and concrete. The generation born during Neptune's transit through Cparicorn will make use of the inspirational ideas of the previous generation, particularly in science, chemistry and medicine. Neptune in this position gives creative insight into things of the earth; These people will find a way not only to use them efficiently but also to conserve and replenish the gifts of the earth.",
    Pluto: "(2008/09- 2024) Because Capricorn is the sign of discipline and ambition, Pluto's influence here should stress responsibility and ethic of work. Capricorn is the sign of government and long-term security. Individual nations may join in a system of world government that leads to greater stability. Pluto in Capricorn holds out the hope there will be and end to war."
}

const Aquarius={
    Mercury: "A native of this position you take great interest in other people and have excellent judgement of human nature. You are a notourious people-watcher. Yours is a broad and emotionally detatchd outlook.",
    Venus: "You have an intellectually detatched attitude toward love. To you, personal freedom is most important, and any relationship must leave you free to explore varied interests and hobbies, meeting new people, and enjoy a wide range of friends. You cannot tolerate jealous and will walk away from emotional scenes.",
    Mars: "In Aquarius, the energy of Mars is expressed on the mental plane. You are quick in your actions, but before you act you must be committed intellectually. High-strung and unpredictable, you struggle between wanting to do things alone and getting involved in group activities.",
    Jupiter: "Jupiter in Aquarius contributes to a magnetic ability to win friends. You usually find good fortune through your friends an unexpected opportunities. You easily become bored when the sole purpose of an activity is to make money. You usually find your best opportunity in professions where a broader view is neccessary.",
    Saturn: "You are likely to run the show and get your own way, and you are clever about manipulating people so you can. You can be obstinate and cunning at the same time. Saturn gives you the aggressiveness to take leadership, but you know how to avoid rubbing others the wrong way.",
    Uranus: "You have a touch of genuis plus the ability to make your impact on a wide group of people. Others are drawn to your unique mind, for you are an advanced thinker. You are a curious blend: You believe in freedom of thought and expression but are convinced that you alone are right.",
    Neptune: "(1998- 2012) In the humanitarian sign of Aquarius, Neptune's power brings high ideals and social justice. Neptune-Aquarians are concerned about the welfare of others less fortunate. This generation will have visionary concepts that they put into practice. Neptune in this position has been called by astrologers \"the flame of conscience.\"",
    Pluto: "Pluto will bring even greater emphasis to humantiarian and freedom-loving qualities of Aquarius. This should be a time of unimaginable scientific discovery, for Aquarius is the sign of science and future knowledge."
}


const Pisces={
    Mercury: "There is an intriguing air of mystery about the way you think. You dont logicallly arrivate at conclusions; you seem to get flashes of knowledge or sudden feelings that are not based on previous facts or circumstances. You have an accurate intuition- Afterwards what you say will turn out to be true.",
    Venus: "In love, you are gentle, kindhearted, extremely sensitive- and fickle. It is not that you mean to be inconsistent. No other position of Venus can be as self-sacrificing or places more importance on the happiness of loved ones. You have true empathy for the problems of another person.",
    Mars: "Pisces is an emotional sign, and your strength with Mars in Pisces is your power to stir the feelings and grab emotions. Enormously receptive to your environment, you store impressions in your subconcious then produce them at the opportune time.",
    Jupiter: "Jupiter is stronger here because it endows you with the power to appeal to the emotions. Work in which you deal directly with others, especially where there is a high level of feeling, will bring success. Jupiter also accentuates your imagination, wisdom and high ideals.",
    Saturn: "Pisces is the sign of self-undoing, and your greatest power comes when you learn not to be the cause of your own happiness. Pisces does not favor material success. What you gain in life are sagacity and discernment.",
    Uranus: "You have a unique talent for understanding and expressing human feelings, which often shows up in creative work. You are blessed with psychic awareness; your intuitions tell you when to act and alret you when others are receptive to your ideas. At times you must withdraw from the world and recharge your psychic batteries.",
    Neptune: "(2012- 2026) In Pisces, Neptune will be in the sign it rules, and therefore its qualities of spirituality and creative genius will be enhanced for those born in this era. Astrologers believe that this generation, born when Neptune next transits Pisces, may usher in the ultimate period of self-realization. Neptune in this position does not value materialism, so Neptune-Pisceans no doubt will explore the inner man and woman, and develop a new philosophy based on what they find.",
    Pluto: "When Pluto is in Pisces, human beings may at last comprehend the fullness of Pluto's power and add to their knowledge of the meaning of life. Pisces represents the completion of the circle, the last step before moving on to the first rung of a higher ladder. By this time the human race may have evolved to a higher and more noble plane."
}

const Element= {
    Fire: "Energetic. Active. Enthusiastic. Passionate. A need to express oneself. Impuslive. Takes the initative. Outgoing. Tends to be extroverted.",
    Earth: "Practical. Stable. Places importance on security. Patient. Industrious. Strong-willed. Able to apply oneself toward long-range goal.",
    Air: "Communicative. Intelligent. Likes to deal on a mental plane. Quickly grasps ideas. Can speak or write effectively. Takes a rational viewpoint.",
    Water: "Emotional. Intuitive. Sensitve to surroundings and to other people. Creative. Good powers of imagination. Empathetic. A person of hidden depths."    
}
const elementMap = new Map(Object.entries(Element))

const Mode= {
    Cardinal: "Open to change. Emphasis on action. Tries to change environment. Projects self onto surroundings.",
    Fixed: "Resistant to change. Single-minded in pursuits. Not easily swayed. Tries to mold environment to the will.",
    Mutable: "Changeable and flexible. Mentally explorative. Emphasis on intellectual activity. Adaptable to the environment."
}